# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_USER: []
        ROLE_ADMIN: [ROLE_USER]
        ROLE_MANAGER_BLOG: [ROLE_USER]
        ROLE_ADMIN_MANAGER: [ROLE_ADMIN, ROLE_MANAGER_BLOG]
        ROLE_SUPER_ADMIN: [ROLE_MANAGER_BLOG, ROLE_ADMIN_MANAGER]

    encoders:
        RestBundle\Entity\User:
            algorithm: bcrypt

        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db:
            entity:
                class: RestBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        download_attachment_from_email:
            pattern: ^/api/v1/download/attachment/email/*
            anonymous: true

        api:
            pattern: ^/api/v1/profile/*
            stateless: true
            simple_preauth:
                authenticator: api.authenticator
            provider: user_db

        homepage:
            pattern: ^/api/v1/homepage/*
            stateless: true
            simple_preauth:
                authenticator: api.authenticator
            provider: user_db

        download:
            pattern: ^/api/v1/download/*
            stateless: true
            simple_preauth:
                authenticator: api.authenticator
            provider: user_db

        favorite:
            pattern: ^/api/v1/favorites/*
            stateless: true
            simple_preauth:
                authenticator: api.authenticator
            provider: user_db

        jobs:
            pattern: ^/api/v1/job/*
            stateless: true
            simple_preauth:
                authenticator: api.authenticator
            provider: user_db

        api:
            pattern: ^/api/v1/*
            anonymous: ~


        admin:
            pattern: ^/
            anonymous: ~
            simple_form:
                provider: user_db
                authenticator: admin_authenticator
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /admin
                remember_me:    true
            logout:
                path: /admin/logout
                target: /admin

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/admins/*, roles: ROLE_ADMIN_MANAGER }
        - { path: ^/admin/services/*, roles: ROLE_ADMIN_MANAGER }
        - { path: ^/admin/settings, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/settings/*, roles: ROLE_ADMIN_MANAGER }
        - { path: ^/admin/templates/*, roles: ROLE_ADMIN_MANAGER }
        - { path: ^/admin/blogs/*, roles: ROLE_MANAGER_BLOG }
        - { path: ^/admin/pages/*, roles: ROLE_ADMIN_MANAGER }
        - { path: ^/admin/testimonials/*, roles: ROLE_ADMIN_MANAGER }
        - { path: ^/admin/users/*, roles: ROLE_ADMIN }
        - { path: ^/admin/*, roles: [ROLE_ADMIN, ROLE_MANAGER_BLOG] }
