RestBundle\Entity\Page:
    exclusion_policy: ALL
    properties:
        title:
            expose: true
            groups: ['list', 'details', 'page', 'random_blog', 'top']

        seo_title:
            expose: true
            groups: ['details', 'page']

        description:
            expose: true
            groups: ['list', 'details', 'page', 'random_blog']

        content:
            expose: true
            groups: ['details']

        image:
            expose: true
            groups: ['list', 'details', 'page', 'random_blog', 'top']

        post_date:
            expose: true
            groups: ['list', 'details']

        slug:
            expose: true
            groups: ['list', 'details', 'random_blog', 'top']
