<?php

namespace MigrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WpPostsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class WpPostsRepository extends EntityRepository
{
    /**
     * @param $id
     * @return array
     */
    public function getAuthorAvatar($id)
    {
        return $this->createQueryBuilder('wp_posts')
            ->where('wp_posts.postParent = :id')
            ->andWhere('wp_posts.postType = :type')
            ->andWhere('wp_posts.postContent = :content')
            ->setParameters([
                'id' => $id,
                'type' => 'attachment',
                'content' => ''
            ])
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $id
     * @return array
     */
    public function getPostTitle($id)
    {
        return $this->createQueryBuilder('wp_posts')
            ->where('wp_posts.postParent = :id')
            ->andWhere('wp_posts.postType = :type')
            ->orderBy('wp_posts.postModified', 'DESC')
            ->setParameters([
                'id' => $id,
                'type' => 'attachment'
            ])
            ->getQuery()
            ->getResult();
    }
}
